print ("Welcome to the Band Name Generator.")
city_name = input("What's name of the city you grew up in? ")
print (city_name)
pet_name = input("What's name of your pet? ")
print (pet_name)
print ("Your Band Name could be: " + city_name+ " " + pet_name)